import { describe, test, expect } from "vitest";
import { generateSimcProfileset } from "./simcProfile";

describe("generateSimcProfileset", () => {
  test("returns empty string when no builds provided", () => {
    expect(
      generateSimcProfileset([], [], "Death Knight", "Blood", null, []),
    ).toBe("");
  });

  test("uses provided build names and sanitizes quotes/backslashes", () => {
    const builds = ["buildString1", "buildString2"];
    const names = ['My "Awesome" Build\\', "Normal Build"];
    const out = generateSimcProfileset(
      builds,
      names,
      "Death Knight",
      "Blood",
      null,
      [],
    );
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."My Awesome Build"+=talents=buildString1\nprofileset."Normal Build"+=talents=buildString2`,
    );
  });

  test("generates fallback names with hero spec prefix when names are empty", () => {
    const builds = ["buildString1"];
    const names = [""];
    const treeData = {
      nodes: [
        {
          id: 101,
          treeType: "hero",
          name: "Hero Node",
          heroSubtree: "San'layn",
        },
      ],
    };
    const parsedBuilds = [
      {
        nodes: { 101: { pointsInvested: 1 } },
      },
    ];

    const out = generateSimcProfileset(
      builds,
      names,
      "Death Knight",
      "Blood",
      treeData,
      parsedBuilds,
    );

    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Build 1 — San'layn Blood Death Knight"+=talents=buildString1`,
    );
  });

  test("generates basic fallback name when spec/class names are absent", () => {
    const builds = ["buildString1"];
    const out = generateSimcProfileset(builds, [], "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Build 1"+=talents=buildString1`,
    );
  });

  test("disambiguates duplicate names so no profileset overwrites another", () => {
    const builds = ["buildA", "buildB", "buildC"];
    const names = ["Raid", "Raid", "Raid"];
    const out = generateSimcProfileset(builds, names, "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Raid"+=talents=buildA\nprofileset."Raid (2)"+=talents=buildB\nprofileset."Raid (3)"+=talents=buildC`,
    );
  });

  test("disambiguates names that collide only after quote-stripping", () => {
    const builds = ["buildA", "buildB"];
    const names = ["Raid", '"Raid"'];
    const out = generateSimcProfileset(builds, names, "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Raid"+=talents=buildA\nprofileset."Raid (2)"+=talents=buildB`,
    );
  });
});
