/**
 * src/lib/wireLayout.js
 *
 * Computes a fingerprint of a class's build-string "wire layout" — the ordered
 * set of node IDs (with their rank/choice arity) that determines every node's
 * bit position in a serialised build string.
 *
 * Why this exists: the app derives the serialisation node set from the data via
 * collectClassNodes(). If a data edit (or a source swap) adds, removes, or
 * reorders a node, OR changes a node's maxRanks / choice count, then every
 * existing build string for that class shifts its bit positions and silently
 * misparses — no error, just wrong talents and broken share links.
 *
 * Two consumers share this one fingerprint:
 *   - The committed snapshot (wireLayout.snapshot.json) turns an accidental
 *     wire-layout change into a loud test failure at build time.
 *   - Share links embed the current hash as a detect-only patch stamp; opening a
 *     link whose stamp no longer matches the live data warns the user instead of
 *     rendering a silently-misparsed build (see buildsStore.js + App.jsx). The
 *     stamp must be class-level (collectClassNodes spans every spec) so it also
 *     catches drift introduced by a sibling spec.
 *
 * Because that runtime stamp runs in the browser, the SHA-256 below is pure JS
 * (no node:crypto), kept byte-for-byte compatible with the snapshot previously
 * generated by node:crypto — pinned by dataIntegrity.test.js.
 */

import { collectClassNodes } from "./buildString.js";

// Vendored compact SHA-256 (public-domain "tiny-sha256"). Synchronous and
// dependency-free so wireLayout() runs in the browser as well as in Node:
// node:crypto isn't available client-side and crypto.subtle is async. Operates
// on Latin-1/ASCII input, which the wire-layout signature always is.
function sha256Hex(ascii) {
  function rightRotate(value, amount) {
    return (value >>> amount) | (value << (32 - amount));
  }

  const mathPow = Math.pow;
  const maxWord = mathPow(2, 32);
  const lengthProperty = "length";
  let i, j;
  let result = "";
  const words = [];
  const asciiBitLength = ascii[lengthProperty] * 8;

  let hash = sha256Hex.h;
  let k = sha256Hex.k;
  if (!hash) {
    hash = sha256Hex.h = [];
    k = sha256Hex.k = [];
    let primeCounter = 0;
    const isComposite = {};
    for (let candidate = 2; primeCounter < 64; candidate++) {
      if (!isComposite[candidate]) {
        for (i = 0; candidate * i < 313; i++) {
          isComposite[candidate * i] = candidate;
        }
        hash[primeCounter] = (mathPow(candidate, 0.5) * maxWord) | 0;
        k[primeCounter++] = (mathPow(candidate, 1 / 3) * maxWord) | 0;
      }
    }
  }

  const asciiLength = ascii[lengthProperty];
  for (i = 0; i < asciiLength; i++) {
    words[i >> 2] |= (ascii.charCodeAt(i) & 0xff) << (24 - (i % 4) * 8);
  }
  words[asciiLength >> 2] |= 0x80 << (24 - (asciiLength % 4) * 8);
  words[(((asciiLength + 8) >> 6) << 4) + 15] = asciiBitLength;

  const currentHash = hash.slice(0);
  const w = [];
  const wordsLength = words[lengthProperty];
  for (i = 0; i < wordsLength; i += 16) {
    const s = currentHash.slice(0);
    for (j = 0; j < 64; j++) {
      let w15, w2;
      if (j < 16) {
        w[j] = words[i + j] | 0;
      } else {
        w15 = w[j - 15];
        w2 = w[j - 2];
        const a = rightRotate(w15, 7) ^ rightRotate(w15, 18) ^ (w15 >>> 3);
        const b = rightRotate(w2, 17) ^ rightRotate(w2, 19) ^ (w2 >>> 10);
        w[j] = (w[j - 16] + a + w[j - 7] + b) | 0;
      }
      const temp1 =
        (s[7] +
          (rightRotate(s[4], 6) ^
            rightRotate(s[4], 11) ^
            rightRotate(s[4], 25)) +
          ((s[4] & s[5]) ^ (~s[4] & s[6])) +
          k[j] +
          w[j]) |
        0;
      const temp2 =
        (rightRotate(s[0], 2) ^ rightRotate(s[0], 13) ^ rightRotate(s[0], 22)) +
        (((s[0] & s[1]) ^ (s[0] & s[2]) ^ (s[1] & s[2])) | 0);

      s[7] = s[6];
      s[6] = s[5];
      s[5] = s[4];
      s[4] = (s[3] + temp1) | 0;
      s[3] = s[2];
      s[2] = s[1];
      s[1] = s[0];
      s[0] = (temp1 + temp2) | 0;
    }
    for (j = 0; j < 8; j++) {
      currentHash[j] = (currentHash[j] + s[j]) | 0;
    }
  }

  for (i = 0; i < 8; i++) {
    for (j = 3; j >= 0; j--) {
      const b = (currentHash[i] >> (j * 8)) & 255;
      result += (b < 16 ? "0" : "") + b.toString(16);
    }
  }
  return result;
}

/**
 * @param {object} classData  Parsed src/data/{slug}.json
 * @returns {{ count: number, hash: string }}  Stable fingerprint of the wire layout
 */
export function wireLayout(classData) {
  const nodes = collectClassNodes(classData);
  // id + maxRanks + choice arity + each choice option's maxRanks fully determine
  // a node's bit footprint AND how its rank decodes: parseBuildString resolves a
  // full-rank pick of a choice option via choices[entryChosen].maxRanks, so a
  // change to an option's maxRanks silently alters decoded pointsInvested without
  // shifting any bit position. Including the per-option maxRanks here makes the
  // snapshot catch that drift too. Joined in collectClassNodes' ascending-id order.
  const signature = nodes
    .map(
      (n) =>
        `${n.id}:${n.maxRanks}:${n.choices?.length ?? 0}:${
          n.choices?.map((o) => o.maxRanks).join(",") ?? ""
        }`,
    )
    .join("|");
  return {
    count: nodes.length,
    hash: sha256Hex(signature).slice(0, 16),
  };
}
